a = int(input("Enter the first number:"))
b = int(input("Enter the second number"))
print("The sum of two numbers:",a+b)
print("The difference of two numbers:",a-b)
print("The product of two numbers:",a*b)
print("The quotient of two numbers:",a/b)
print("The reminder of two numbers",a%b)